### ISSUE TITLE
FEDEFL-Adapted LCIA Methods 404 not found

### ISSUE THREAD

**Issue by M-LAMONT** [FLCAC-admin/FLCAC-docs#15]
The FEDEFL-Adapted LCIA Methods folder appears to be broken,

https://github.com/FLCAC-admin/uslci-content/tree/dev/docs/methods

![image](https://github.com/user-attachments/assets/ecc2dac4-4b09-45c1-b88f-dc3843450af0)

**Comment by bl-young** [comment]
Must of the content has moved from [`uslci-content`](https://github.com/FLCAC-admin/uslci-content/tree/dev) to [`flcac-docs`](https://github.com/FLCAC-admin/FLCAC-docs).

See https://flcac-admin.github.io/FLCAC-docs/lciamethods

Do you recall what link pointed you to this site? We are trying to update pointers to the correct location.

**Comment by M-LAMONT** [comment]
Hi Ben,

The link was here (File not found<https://github.com/FLCAC-admin/uslci-content/tree/dev/docs/methods>)
***@***.***

**Comment by M-LAMONT** [comment]
I navigated to it from here (which I accessed from a websearch): Home * FLCAC-admin/uslci-content Wiki<https://github.com/FLCAC-admin/uslci-content/wiki>, and used the popular link drop list.
